version: '3'

services:
  voice-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    restart: unless-stopped 